### ISSUE TITLE
RandVar segfault

### ISSUE THREAD

**Issue by fgvieira** [RAHenriksen/NGSNGS#41]
When running:
```
RandVar --input /tmp/GCA_000001405.29_GRCh38.p14.fas --modulus 1000 --pos h_sapiens.pos --output h_sapiens.fas
```

I get:
```
Segmentation fault
```

**Comment by RAHenriksen** [comment]
The segmentation fault was due to the calculation of number of variations, which was solely done for the last contig size within the input reference file. It has now been changed such that you can  use 3 methods to determine the number of random variations to be inserted.  Either by providing a fixed number of variations, or by determining the number of variations from the full genome length using division or modulus operator. The number of variations depending on the method will now vary slightly as seen in the example below.

./RandVar --input ../../GCA_000001405.29_GRCh38.p14.fas --number 1000 --pos h_sapiens.pos --output h_sapiens.fas
	-> Number of nref 709 in file: '../../GCA_000001405.29_GRCh38.p14.fas'
	-> Full genome length 3298912062 with 1000 variations to be included 
head -3 h_sapiens.pos 
CM000663.2 	 4720185 	 ref 	 A 	 alt 	 G
CM000664.2 	 93343112 	 ref 	 a 	 alt 	 G
CM000664.2 	 105589543 	 ref 	 C 	 alt 	 G
 
 ./RandVar --input ../../GCA_000001405.29_GRCh38.p14.fas --division 1000 --pos h_sapiens.pos --output h_sapiens.fas
	-> Number of nref 709 in file: '../../GCA_000001405.29_GRCh38.p14.fas'
	-> Full genome length 3298912062 with 3298912 variations to be included 
head h_sapiens.pos 
CM000663.2 	 12915 	 ref 	 T 	 alt 	 C
CM000663.2 	 61914 	 ref 	 t 	 alt 	 A
CM000663.2 	 107763 	 ref 	 a 	 alt 	 T

./RandVar --input ../../GCA_000001405.29_GRCh38.p14.fas --modulus 1000 --pos h_sapiens.pos --output h_sapiens.fas
	-> Number of nref 709 in file: '../../GCA_000001405.29_GRCh38.p14.fas'
	-> Full genome length 3298912062 with 3298913 variations to be included 
(base) [wql443@dandycomp02fl misc]$ head h_sapiens.pos 
CM000663.2 	 12915 	 ref 	 T 	 alt 	 C
CM000663.2 	 61914 	 ref 	 t 	 alt 	 A
CM000663.2 	 107763 	 ref 	 a 	 alt 	 T

NOTE: due to the remainder there will be slight variations between modulus and division, with division being faster.
